server:
  port: 8099
spring:
  application:
    name: shopping-micro-gateway
  cloud:
    gateway:
      routes:
        - id: gateway-service
          uri: https://www.baidu.com
          predicates:
            - Path=/meteor_93



